language: ruby
sudo: false
cache: bundler
before_script:
  - bundle update
  - middleman build
  - git add .
  - git commit -m 'content build'
  - git push origin master
rvm:
  - ruby-head
os:
  - linux
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
