# If you do not have OpenSSL installed, update
# the following line to use "http://" instead
source 'https://rubygems.org'

# Specify your gem's dependencies in middleman-datasource.gemspec
gemspec

group :development do
  gem 'rake'
  gem 'rdoc'
  gem 'yard'
  gem 'google-api-client'
  gem 'google_drive'
  gem 'nokogiri'
end

group :test do
  gem 'cucumber'
  gem 'aruba'
  gem 'rspec'
end
